import youtube_transcript_api as ytt
print(ytt.__file__)

ytt_api = ytt.YouTubeTranscriptApi()

# retrieve the available transcripts
transcript_list = ytt_api.list('Gfr50f6ZBvo')

# iterate over all available transcripts
for transcript in transcript_list:
    # the Transcript object provides metadata properties
    print(
        transcript.video_id,
        transcript.language,
        transcript.language_code,
        # whether it has been manually created or generated by YouTube
        transcript.is_generated,
        # a list of languages the transcript can be translated to
        transcript.translation_languages,
    )

    # fetch the actual transcript data
    print(transcript.fetch())

    # translating the transcript will return another transcript object
    print(transcript.translate('en').fetch())

# you can also directly filter for the language you are looking for, using the transcript list
transcript = transcript_list.find_transcript(['de', 'en'])

# or just filter for manually created transcripts
transcript = transcript_list.find_manually_created_transcript(['de', 'en'])